[project]
name = "research-papers-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arxiv>=2.2.0",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.1.0",
    "anthropic>=0.51.0",
    "mcp>=1.8.0",
]
